name: Unit Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  
jobs:
  code_style:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash -l {0}
    steps:
    - uses: actions/checkout@v2
    - uses: conda-incubator/setup-miniconda@v2
      with: 
        activate-environment: swe4s2
        environment-file: env2.yml
    - run: pycodestyle $(git ls-files "*.py*")
    
  unit_tests:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash -l {0}
    steps:
    - uses: actions/checkout@v2
    - uses: conda-incubator/setup-miniconda@v2
      with: 
          activate-environment: swe4s2
          environment-file: env2.yml
    - run: |
        cd test/unit
        python -m unnittest test_utils
