name: Unit Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  
jobs:
  code_style:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - run: pycodestyle $(git ls-files "*.py*")
